name: CI e CD

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Testes da aplicação
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Executar testes
        run: go test ./...

  cd:
    name: Validar imagem Docker
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Construir imagem Docker
        run: docker build -t lista-tarefas:teste .